<?php

namespace App\Jobs;

use App\Models\Document;
use App\Services\Ai\ProjectAiService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProcessDocumentAI implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(public Document $document) {}

    public function handle(ProjectAiService $aiService)
    {
        // 1. Run the AI service logic
        $result = $aiService->process($this->document);

        if (isset($result['status']) && $result['status'] === 'success') {
            $generatedItems = $result['mock_response'] ?? [];
            $outputType = $result['output_type']; // Dynamically resolved from the Strategy

            // 2. Persist the results as new documents
            DB::transaction(function () use ($generatedItems, $outputType) {

                // Cleanup: Delete previous docs of this type generated by THIS intake document
                Document::where('parent_id', $this->document->id)
                    ->where('type', $outputType)
                    ->delete();

                foreach ($generatedItems as $data) {
                    $this->document->project->documents()->create([
                        'parent_id' => $this->document->id,
                        'type'      => $outputType,
                        'name'      => $data['title'] ?? 'Untitled Deliverable',
                        'content'   => $data['story'] ?? '',
                        // Save criteria or extra AI data in the metadata JSON column
                        'metadata'  => [
                            'criteria' => $data['criteria'] ?? []
                        ],
                    ]);
                }
            });
        }

        // 3. Mark the intake document as processed
        $this->document->update(['processed_at' => now()]);
    }
}
